format:
  pdf:
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{breaklines,breakanywhere}